#!/usr/bin/env python3
"""Rebuild ../ASD-STE100-53-rules.md from ../ASD-STE100_ISSUE9.pdf.

The rule statements as printed on the "Summary of the rules" page that opens
each of the nine sections of Part 1. There is one such page per section, and
the statements on it are the rules themselves, not a paraphrase.

Two things make the extraction awkward, both handled below:

  * When a section's summary is short it shares a printed page with the start
    of the section body, and the body repeats rule X.1 in full. There is no
    footer between the two, so the boundary is found by the repeated rule
    number rather than by the page break. Without that, six duplicates come
    through and the count reads 59 instead of 53.
  * Section 7's summary lists a "Definitions" heading with no rules under it,
    because the warning/caution definitions are prose. Empty headings are
    dropped.

The count is the check: 14 + 2 + 7 + 5 + 5 + 6 + 3 + 7 + 4 = 53.

Usage: python3 scripts/extract_rules.py
"""
import re
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PDF = ROOT / "ASD-STE100_ISSUE9.pdf"
OUT = ROOT / "ASD-STE100-53-rules.md"
ISSUE, ISSUE_DATE = "Issue 9", "2025-01-15"

SECTIONS = [
    "Words",
    "Multi-word nouns",
    "Verbs",
    "Sentences",
    "Procedural writing",
    "Descriptive writing",
    "Safety instructions",
    "Punctuation and word count",
    "Writing practices",
]
PER_SECTION = [14, 2, 7, 5, 5, 6, 3, 7, 4]

RULE = re.compile(r"^\s*Rule (\d+)\.(\d+)\s+(.*)$")
FOOTER = re.compile(r"Page 1-\d+-1\s*$|^\s*Issue 9\s")
CONTINUATION_INDENT = 10


def layout_text():
    with tempfile.TemporaryDirectory() as tmp:
        out = Path(tmp) / "full.txt"
        subprocess.run(["pdftotext", "-layout", str(PDF), str(out)], check=True)
        return out.read_text(encoding="utf-8")


def sections(text):
    lines = text.split("\n")
    starts = [i for i, l in enumerate(lines) if l.strip() == "Summary of the rules"]
    if len(starts) != 9:
        sys.exit(f"expected 9 summary pages, found {len(starts)}")

    for index, start in enumerate(starts):
        entries, seen = [], set()
        for line in lines[start + 1:]:
            if FOOTER.search(line):
                break
            if not line.strip():
                continue
            m = RULE.match(line)
            if m:
                number = f"{m.group(1)}.{m.group(2)}"
                if number in seen:
                    break          # the body repeats it: the summary ended here
                seen.add(number)
                entries.append(["rule", number, [m.group(3).strip()]])
            elif (
                len(line) - len(line.lstrip()) >= CONTINUATION_INDENT
                and entries
                and entries[-1][0] == "rule"
            ):
                entries[-1][2].append(line.strip())
            else:
                entries.append(["head", line.strip()])

        while entries and entries[-1][0] == "head":
            entries.pop()          # a body heading pulled in before the break

        yield index, [e for i, e in enumerate(entries)
                      if e[0] == "rule" or any(
                          f[0] == "rule" for f in entries[i + 1:i + 2]
                      ) or has_rule_after(entries, i)]


def has_rule_after(entries, i):
    """Keep a heading only when a rule follows it before the next heading."""
    for e in entries[i + 1:]:
        if e[0] == "rule":
            return True
        if e[0] == "head":
            return False
    return False


def render(text):
    out, counts = [], []
    for index, entries in sections(text):
        out.append(f"\n## Section {index + 1} — {SECTIONS[index]}\n")
        n = 0
        for e in entries:
            if e[0] == "head":
                out.append(f"\n### {e[1]}\n")
                continue
            n += 1
            parts = e[2]
            body = " ".join(p for p in parts if not p.startswith("-"))
            out.append(f"- **Rule {e[1]}** — {body}")
            for bullet in (p for p in parts if p.startswith("-")):
                out.append(f"    - {bullet.lstrip('- ').rstrip('.')}")
        counts.append(n)
    return out, counts


HEADER = f"""# ASD-STE100 — the 53 writing rules

Simplified Technical English, {ISSUE}, {ISSUE_DATE}. Rule statements as printed
in the "Summary of the rules" page of each section in Part 1 — Writing rules.

Generated by scripts/extract_rules.py from ASD-STE100_ISSUE9.pdf; do not edit
by hand. The standard is not carried in this repository; see the Getting the
standard section of README.md.

The rule statements alone are reproduced here. Each rule in the specification
is followed by explanatory text, examples, and (new in Issue 9) "Help" notes
that this file does not include; read Part 1 of the PDF for those. The approved
dictionary is Part 2.

Copyright: ASD-STE100 is a copyright and an EU trademark of ASD, Brussels
(EU Trade Mark No. 017966390). ASD gives the specification free of charge but
forbids reproduction in whole or in part without written authority, except for
the organizations listed under "Special usage rights" in the PDF front matter.
Treat this file as a local working reference, not as redistributable content.

Sections: 1 Words · 2 Multi-word nouns · 3 Verbs · 4 Sentences ·
5 Procedural writing · 6 Descriptive writing · 7 Safety instructions ·
8 Punctuation and word count · 9 Writing practices
"""


def main():
    if not PDF.exists():
        sys.exit(
            f"{PDF.name} is not here.\n"
            "The standard is not carried in this repository.\n"
            "Request your own copy from the form at\n"
            "    https://www.asd-ste100.org/STE_downloads.html\n"
            f"and save it as {PDF}\n"
            "See the Getting the standard section of README.md for why."
        )
    body, counts = render(layout_text())
    total = sum(counts)
    if counts != PER_SECTION:
        sys.exit(f"rule counts per section are {counts}, expected {PER_SECTION}")
    if total != 53:
        sys.exit(f"found {total} rules, expected 53")
    text = re.sub(r"\n{3,}", "\n\n", "".join(HEADER) + "\n" + "\n".join(body)).strip()
    OUT.write_text(text + "\n", encoding="utf-8")
    print(f"{OUT.name}: {total} rules, {counts} per section")


if __name__ == "__main__":
    main()
